services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: applications
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
